[workspace]
members = [
    "src/day1",
    "src/day2",
    "src/day3",
    "src/day4",
    "src/day5",
    "src/day6",
    "src/day7",
    "src/day8",
    "src/day9",
    "src/day10",
    "src/day11",
    "src/day12",
    "src/test_others"
]
